"""
CUSTOMIZATION GUIDE - How to Customize Clients, Rounds, and Routers
"""

def show_customization_guide():
    """
    Show complete guide on how to customize the FHE data flow
    """
    print("🔧 CUSTOMIZATION GUIDE - CLIENTS, ROUNDS, AND ROUTERS")
    print("="*80)
    
    print("\n📋 WHAT YOU CAN CUSTOMIZE:")
    print("-" * 35)
    print("  👥 Number of Clients (Smartwatches)")
    print("  🔄 Number of Federated Learning Rounds")
    print("  🏠 Number of Home Routers")
    print("  📊 Data Source (Real CSV vs Synthetic)")
    print("  🛠️  Feature Engineering (47 features vs Basic)")
    print("  📝 Verbose Output (Detailed vs Summary)")
    
    print("\n🎯 CONFIGURATION EXAMPLES:")
    print("-" * 30)
    
    print("\n1️⃣ SMALL SCALE EXPERIMENT:")
    print("  👥 Clients: 3")
    print("  🔄 Rounds: 2")
    print("  🏠 Routers: 1")
    print("  📊 Data: Real CSV")
    print("  🛠️  Features: 47 (Advanced)")
    print("  ⏱️  Expected Time: ~2-3 seconds")
    print("  🎯 Use Case: Quick testing, development")
    
    print("\n2️⃣ MEDIUM SCALE EXPERIMENT:")
    print("  👥 Clients: 8")
    print("  🔄 Rounds: 5")
    print("  🏠 Routers: 2")
    print("  📊 Data: Real CSV")
    print("  🛠️  Features: 47 (Advanced)")
    print("  ⏱️  Expected Time: ~8-12 seconds")
    print("  🎯 Use Case: Standard research experiments")
    
    print("\n3️⃣ LARGE SCALE EXPERIMENT:")
    print("  👥 Clients: 15")
    print("  🔄 Rounds: 10")
    print("  🏠 Routers: 3")
    print("  📊 Data: Real CSV")
    print("  🛠️  Features: 47 (Advanced)")
    print("  ⏱️  Expected Time: ~20-30 seconds")
    print("  🎯 Use Case: Comprehensive research, scalability studies")
    
    print("\n4️⃣ FAST EXPERIMENT:")
    print("  👥 Clients: 4")
    print("  🔄 Rounds: 3")
    print("  🏠 Routers: 1")
    print("  📊 Data: Synthetic")
    print("  🛠️  Features: 14 (Basic)")
    print("  ⏱️  Expected Time: ~1-2 seconds")
    print("  🎯 Use Case: Quick validation, debugging")
    
    print("\n🔧 HOW TO CUSTOMIZE:")
    print("-" * 25)
    
    print("\n📝 METHOD 1: Edit the Configuration in the Script")
    print("  ```python")
    print("  # In run_customizable_fhe_data_flow.py")
    print("  config = CustomConfig(")
    print("      num_clients=10,        # Your desired number of clients")
    print("      num_rounds=7,          # Your desired number of rounds")
    print("      num_routers=2,         # Your desired number of routers")
    print("      use_real_data=True,    # True for CSV, False for synthetic")
    print("      feature_engineering=True, # True for 47 features, False for basic")
    print("      verbose=True           # True for detailed output")
    print("  )")
    print("  ```")
    
    print("\n📝 METHOD 2: Create Your Own Configuration")
    print("  ```python")
    print("  # Create custom configuration")
    print("  my_config = CustomConfig(")
    print("      num_clients=12,        # 12 smartwatches")
    print("      num_rounds=6,          # 6 federated learning rounds")
    print("      num_routers=2,         # 2 home routers")
    print("      use_real_data=True,    # Use real health data")
    print("      feature_engineering=True, # Use advanced features")
    print("      verbose=True           # Show detailed progress")
    print("  )")
    print("  ")
    print("  # Run with your configuration")
    print("  success = run_customizable_fhe_data_flow(my_config)")
    print("  ```")
    
    print("\n📝 METHOD 3: Command Line Arguments (Advanced)")
    print("  ```python")
    print("  import sys")
    print("  ")
    print("  # Parse command line arguments")
    print("  clients = int(sys.argv[1]) if len(sys.argv) > 1 else 6")
    print("  rounds = int(sys.argv[2]) if len(sys.argv) > 2 else 3")
    print("  routers = int(sys.argv[3]) if len(sys.argv) > 3 else 2")
    print("  ")
    print("  config = CustomConfig(")
    print("      num_clients=clients,")
    print("      num_rounds=rounds,")
    print("      num_routers=routers")
    print("  )")
    print("  ```")
    
    print("\n⚙️ CONFIGURATION PARAMETERS:")
    print("-" * 35)
    
    print("\n👥 num_clients (Number of Smartwatches):")
    print("  📊 Range: 1-50 (recommended: 3-15)")
    print("  🎯 Impact: More clients = more data diversity")
    print("  ⏱️  Time Impact: Linear increase")
    print("  💡 Tip: Start with 3-6 for testing")
    
    print("\n🔄 num_rounds (Federated Learning Rounds):")
    print("  📊 Range: 1-20 (recommended: 3-10)")
    print("  🎯 Impact: More rounds = better convergence")
    print("  ⏱️  Time Impact: Linear increase")
    print("  💡 Tip: 3-5 rounds usually sufficient")
    
    print("\n🏠 num_routers (Home Routers):")
    print("  📊 Range: 1-5 (recommended: 1-3)")
    print("  🎯 Impact: More routers = better load distribution")
    print("  ⏱️  Time Impact: Minimal")
    print("  💡 Tip: 1-2 routers sufficient for most cases")
    
    print("\n📊 use_real_data (Data Source):")
    print("  📊 Options: True (CSV) or False (Synthetic)")
    print("  🎯 Impact: Real data = more realistic results")
    print("  ⏱️  Time Impact: Real data slightly slower")
    print("  💡 Tip: Use real data for research, synthetic for testing")
    
    print("\n🛠️ feature_engineering (Feature Complexity):")
    print("  📊 Options: True (47 features) or False (14 features)")
    print("  🎯 Impact: More features = better accuracy")
    print("  ⏱️  Time Impact: More features = slightly slower")
    print("  💡 Tip: Use 47 features for research, 14 for quick tests")
    
    print("\n📝 verbose (Output Detail):")
    print("  📊 Options: True (Detailed) or False (Summary)")
    print("  🎯 Impact: Detailed output = better debugging")
    print("  ⏱️  Time Impact: None")
    print("  💡 Tip: Use True for development, False for batch runs")
    
    print("\n🚀 QUICK START EXAMPLES:")
    print("-" * 30)
    
    print("\n💻 Command 1: Run Default Configuration")
    print("  python run_customizable_fhe_data_flow.py")
    print("  # Uses: 4 clients, 3 rounds, 1 router, synthetic data")
    
    print("\n💻 Command 2: Edit Configuration in Script")
    print("  # 1. Open run_customizable_fhe_data_flow.py")
    print("  # 2. Find the config = config_fast line")
    print("  # 3. Change to config = config_medium")
    print("  # 4. Run: python run_customizable_fhe_data_flow.py")
    
    print("\n💻 Command 3: Create Custom Configuration")
    print("  # 1. Create new file: my_custom_experiment.py")
    print("  # 2. Copy configuration code")
    print("  # 3. Modify parameters")
    print("  # 4. Run: python my_custom_experiment.py")
    
    print("\n📊 EXPECTED RESULTS BY CONFIGURATION:")
    print("-" * 45)
    
    print("\n🔬 SMALL SCALE (3 clients, 2 rounds, 1 router):")
    print("  📊 Accuracy: 85-90%")
    print("  ⏱️  Time: 2-3 seconds")
    print("  🔐 Encryption: ~0.01s")
    print("  ☁️  Aggregation: ~0.1s")
    
    print("\n🔬 MEDIUM SCALE (8 clients, 5 rounds, 2 routers):")
    print("  📊 Accuracy: 88-92%")
    print("  ⏱️  Time: 8-12 seconds")
    print("  🔐 Encryption: ~0.05s")
    print("  ☁️  Aggregation: ~0.3s")
    
    print("\n🔬 LARGE SCALE (15 clients, 10 rounds, 3 routers):")
    print("  📊 Accuracy: 89-93%")
    print("  ⏱️  Time: 20-30 seconds")
    print("  🔐 Encryption: ~0.1s")
    print("  ☁️  Aggregation: ~0.6s")
    
    print("\n🔬 FAST EXPERIMENT (4 clients, 3 rounds, 1 router, synthetic):")
    print("  📊 Accuracy: 80-85%")
    print("  ⏱️  Time: 1-2 seconds")
    print("  🔐 Encryption: ~0.005s")
    print("  ☁️  Aggregation: ~0.05s")
    
    print("\n🎯 RECOMMENDATIONS BY USE CASE:")
    print("-" * 40)
    
    print("\n🧪 RESEARCH PAPER:")
    print("  👥 Clients: 8-12")
    print("  🔄 Rounds: 5-8")
    print("  🏠 Routers: 2-3")
    print("  📊 Data: Real CSV")
    print("  🛠️  Features: 47 (Advanced)")
    print("  📝 Output: Detailed")
    
    print("\n🔬 SCALABILITY STUDY:")
    print("  👥 Clients: 5, 10, 15, 20")
    print("  🔄 Rounds: 5")
    print("  🏠 Routers: 2")
    print("  📊 Data: Real CSV")
    print("  🛠️  Features: 47 (Advanced)")
    print("  📝 Output: Summary")
    
    print("\n🧪 QUICK TESTING:")
    print("  👥 Clients: 3-4")
    print("  🔄 Rounds: 2-3")
    print("  🏠 Routers: 1")
    print("  📊 Data: Synthetic")
    print("  🛠️  Features: 14 (Basic)")
    print("  📝 Output: Detailed")
    
    print("\n🔬 PERFORMANCE BENCHMARKING:")
    print("  👥 Clients: 10")
    print("  🔄 Rounds: 10")
    print("  🏠 Routers: 3")
    print("  📊 Data: Real CSV")
    print("  🛠️  Features: 47 (Advanced)")
    print("  📝 Output: Summary")
    
    print("\n🎉 YOU'RE READY TO CUSTOMIZE!")
    print("-" * 35)
    print("  ✅ Choose your configuration")
    print("  ✅ Edit the parameters")
    print("  ✅ Run the experiment")
    print("  ✅ Analyze the results")
    print("  ✅ Publish your research!")

if __name__ == "__main__":
    show_customization_guide()
